environment:
  GIT_REPOSITORY: https://github.com/sci-bots/microdrop-3
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
      CONDA_CANARY: false

    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
      CONDA_CANARY: false

init:
  - ECHO %PYTHON_VERSION%

install:
  # Setup Conda (Must install in User directory for constructor to work)
  - cmd: set PATH=%MINICONDA%\bin;%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --add channels lucaszw
  - cmd: conda config --add channels sci-bots
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes nodejs=8 binstar

  # Run Tests
  - cmd: node --version
  - cmd: npm install --global yarn lerna npm-check-updates
  - cmd: npm run bootstrap
  - cmd: npm run build
  - cmd: npm run test


build: false
test_script:
  - echo Build Complete
